CREATE TABLE inbound_webhook_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_event_id VARCHAR(255) NOT NULL,
    raw_payload JSONB NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processing_status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    CONSTRAINT inbound_webhook_event_processing_status_check
        CHECK (processing_status IN ('RECEIVED')),
    CONSTRAINT inbound_webhook_event_external_event_id_key UNIQUE (external_event_id)
);
